= Einleitung

Die fortschreitende Entwicklung von Large Language Models eröffnet neue Möglichkeiten für die Unterstützung betrieblicher Prozesse. Sprachmodelle können natürlichsprachliche Anfragen verarbeiten, Informationen zusammenfassen und Antworten formulieren. Durch die Verbindung mit externen Werkzeugen und Datenquellen können sie darüber hinaus Aufgaben bearbeiten, die über die reine Texterzeugung hinausgehen. Solche Systeme werden häufig als agentische Systeme bezeichnet, da sie Aufgaben analysieren, Handlungsschritte ableiten und geeignete Werkzeuge zur Bearbeitung einer Anfrage auswählen können @yao2022react; @wang2024survey; @luo2025large.

Für Unternehmen ergibt sich daraus die Möglichkeit, bestehende Anwendungen durch KI-gestützte Funktionen zu erweitern. Der praktische Nutzen eines Sprachmodells hängt dabei wesentlich davon ab, ob es kontrolliert auf relevante Informationen und Funktionen zugreifen kann. Ohne eine technische Anbindung bleibt das Modell auf die Informationen beschränkt, die ihm innerhalb der jeweiligen Anfrage zur Verfügung gestellt werden. Eine Verbindung zu bestehenden Systemen kann daher dazu beitragen, betriebliche Informationen gezielter bereitzustellen und wiederkehrende Fragestellungen effizienter zu bearbeiten.

In diesem Zusammenhang soll im Unternehmen untersucht werden, ob Simplifier als Model Context Protocol-Server eingesetzt werden kann. Das unternehmensinterne KI-Modell NOVA soll dadurch mit zusätzlichen Funktionen und Systemzugriffen ausgestattet werden. NOVA soll künftig bei standardisierten internen Themen unterstützen, relevante Informationen abrufen und auf dieser Grundlage Vorschläge für das weitere Vorgehen erstellen können. Simplifier übernimmt dabei die Rolle einer technischen Schnittstelle, über die ausgewählte Funktionen für NOVA bereitgestellt werden.

Die betriebliche Problemstellung besteht darin, dass bisher nicht abschließend geklärt ist, ob und unter welchen Voraussetzungen Simplifier als MCP-Server für NOVA eingesetzt werden kann. Offen ist insbesondere, wie die technische Verbindung umgesetzt werden kann, welche Funktionen bereitgestellt werden können und welche Einschränkungen bei der Nutzung zu berücksichtigen sind. Zusätzlich müssen mögliche Sicherheitsrisiken betrachtet werden, die sich aus dem Zugriff eines KI-Modells auf externe Funktionen und betriebliche Informationen ergeben können. Das Model Context Protocol ist in diesem Zusammenhang von besonderer Bedeutung, da es die standardisierte Verbindung zwischen einem KI-Modell und externen Werkzeugen ermöglichen soll @hou2025model.

Eine systematische Untersuchung dieser Fragestellung wurde bisher nicht durchgeführt. Zwar wurde die vorhandene Dokumentation von Simplifier zur Einrichtung eines MCP-Servers als erste Informationsgrundlage herangezogen, eine praktische prototypische Überprüfung der Verbindung mit NOVA steht jedoch noch aus. Dadurch fehlt dem Unternehmen eine belastbare Entscheidungsgrundlage für die weitere Nutzung von Simplifier im Zusammenhang mit dem unternehmensinternen KI-Modell. Die vorliegende Transferleistung setzt an dieser offenen technischen Fragestellung an und untersucht die Machbarkeit anhand eines begrenzten Anwendungsszenarios.

Zur Bearbeitung der Fragestellung werden eine Literaturanalyse, ein Experteninterview und ein Proof of Concept miteinander verbunden. Die Literaturanalyse dient der Aufarbeitung der technischen und wissenschaftlichen Grundlagen. Durch das Experteninterview werden die betrieblichen Anforderungen und Rahmenbedingungen erfasst. Anschließend wird im Rahmen eines Proof of Concept praktisch geprüft, ob Simplifier als MCP-Server grundsätzlich an NOVA angebunden werden kann und ob NOVA die bereitgestellten Funktionen für standardisierte interne Fragen nutzen kann. Die technische Prüfung orientiert sich dabei am Grundgedanken eines Proof of Concept, bei dem die grundsätzliche Umsetzbarkeit einer technischen Idee unter begrenzten Bedingungen untersucht wird @elliott2021proof.

Die Transferleistung konzentriert sich somit auf die Analyse und praktische Überprüfung der technischen Machbarkeit. Ziel ist nicht die Entwicklung eines vollständig produktiven oder unternehmensweit eingesetzten Systems. Vielmehr soll eine fundierte Einschätzung darüber ermöglicht werden, ob der gewählte Integrationsansatz grundsätzlich weiterverfolgt werden kann und welche technischen sowie sicherheitsbezogenen Anforderungen für eine spätere Umsetzung zu berücksichtigen sind.

Der Aufbau der Transferleistung orientiert sich an den Grundsätzen zur Gliederung wissenschaftlicher Arbeiten nach Ahrens @ahrens2012gliederung. Nach der Einleitung wird zunächst die betriebliche und technische Ausgangssituation analysiert. Anschließend werden die Zielsetzung und die Abgrenzung der Untersuchung erläutert. Darauf folgt die Beschreibung der Methodik. Im Kapitel zur Entwicklung werden die Konzeption und die Umsetzung des Proof of Concept dargestellt. Anschließend werden die Ergebnisse anhand festgelegter Kriterien bewertet. Die Transferleistung schließt mit einer Zusammenfassung der zentralen Erkenntnisse und einem Ausblick auf mögliche weitere Schritte.